language: php

dist: precise

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - PLUGIN_NAME=CsvSimple
    - CAKE_REF=2.x

  matrix:
    - DB=mysql
    # - DB=pgsql


before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh
  - sed -i -e 's@n assertEquals($expected, $actual, $delta = 0, $canonicalize = FALSE, $ignoreCase = FALSE)@n assertEquals($expected, $actual, $delta = 0, $canonicalize = FALSEE, $ignoreCase = FALSE, array \&$processed = array())@' /home/travis/.composer/vendor/phpunit/phpunit/PHPUnit/Framework/Comparator/DOMDocument.php

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
